### ISSUE TITLE
Moto g4 play

### ISSUE THREAD

**Issue by leo26212** [PixysOS/packages_apps_Settings#16]
Love this rom i only have one issue with it... Ive tried everything ik of.. I can receive but not send sms

**Comment by MiguelNdeCarvalho** [comment]
@leo26212 Hey, do you have a logcat so we can see?

**Comment by leo26212** [comment]
I dont tbh im bit of a noob but i catch on fast if someone could point me
in the right direction im sure i can get there... While i wait on a reply
ill see if i can figure it out

**Comment by MiguelNdeCarvalho** [comment]
@leo26212 try to follow this [guide](https://forum.xda-developers.com/showthread.php?t=2274119). If you need more help use my telegram @MiguelNdeCarvalho

**Comment by leo26212** [comment]
01-19 05:37:37.533  2382  2883 I ActivityManager: Process
com.google.android.apps.messaging (pid 5505) has died: cch+4CEM

01-19 05:37:46.667  2382  2399 I ActivityManager: Start proc
9059:com.google.android.apps.messaging/u0a75 for broadcast
com.google.android.apps.messaging/.shared.datamodel.action.execution.PendingActionReceiver

01-19 05:37:47.782  2382  4204 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:48.801  2382  3977 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:48.938  2382  4204 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:49.306  2382  3783 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:49.402  2382  3975 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:49.481  2382  4206 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:50.085  2382  3952 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:50.112  2382  3953 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:50.312  2382  2436 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:50.720  2382  3955 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:50.871  2382  3977 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:53.354  2382  2436 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:53.357  2382  3952 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:54.152  2382  3783 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:54.259  2382  3953 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:55.526  2382  3975 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:37:55.834  2382  4241 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:39:48.948  2382  2771 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:39:51.455  2382  3975 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:39:52.442  2382  3952 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:40:40.432  2382  2434 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
} to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=9059 uid=10075 pkg=com.google.android.apps.messaging startFg?=false

01-19 05:46:31.723  2382  2434 I ActivityManager: Killing
9059:com.google.android.apps.messaging/u0a75 (adj 902): remove task

01-19 06:04:15.874  2382  2882 I ActivityManager: START u0
{act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER]
flg=0x10200000
cmp=com.google.android.apps.messaging/.ui.ConversationListActivity
bnds=[21,748][190,958]} from uid 10006

01-19 06:04:16.143  2382  2399 I ActivityManager: Start proc
14248:com.google.android.apps.messaging/u0a75 for activity
com.google.android.apps.messaging/.ui.ConversationListActivity

01-19 06:04:20.275  2382  4240 I ActivityManager: START u0 {flg=0x4000001
cmp=com.google.android.apps.messaging/.ui.conversation.ConversationActivity}
from uid 10075

01-19 06:04:42.068  2382  2434 W NotificationService: Toast already killed.
pkg=com.google.android.apps.messaging
callback=android.app.ITransientNotification$Stub$Proxy@895670

01-19 06:06:17.835  2382  2436 W ActivityManager: Background start not
allowed: service Intent {
cmp=com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
(has extras) } to
com.google.android.apps.messaging/.shared.datamodel.action.execution.ActionExecutorImpl$EmptyService
from pid=14248 uid=10075 pkg=com.google.android.apps.messaging
startFg?=false

01-19 06:10:40.657 15662 15662 I CarrierServices:
carrier_services_security_flags_ec_api_white_listed_packages:
com.google.android.apps.messaging,com.google.android.dialer,com.google.android.ims.client.sampleapp,com.android.contacts,com.lge.rcscall,com.android.incallui,com.huawei.incallui.appfeature.rcsfeature

01-19 06:10:40.657 15662 15662 I CarrierServices:
carrier_services_security_flags_white_listed_packages:
com.google.android.apps.messaging,com.google.android.dialer,com.google.android.ims.client.sampleapp,com.android.contacts,com.lge.rcscall,com.android.incallui,com.huawei.incallui.appfeature.rcsfeature

01-19 06:10:42.194 14248 14337 W RcsProvisioning: Failed to read
configuration:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:42.195 14248 14337 W RcsProvisioning:
java.io.FileNotFoundException:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:42.195 14248 14337 W RcsProvisioning: at
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.buildRcsState(SourceFile:58)

01-19 06:10:42.195 14248 14337 W RcsProvisioning: at
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.getRcsState(SourceFile:5)

01-19 06:10:42.455 14248 14337 W RcsProvisioning: Failed to read
configuration:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:42.455 14248 14337 W RcsProvisioning:
java.io.FileNotFoundException:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:42.455 14248 14337 W RcsProvisioning: at
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.buildRcsState(SourceFile:64)

01-19 06:10:42.455 14248 14337 W RcsProvisioning: at
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.getRcsState(SourceFile:5)

01-19 06:10:42.559 14248 14337 E BugleRcsEngine: [527] meb.getFile: File
not found.:
/data/user/0/com.google.android.apps.messaging/files/httpft_pending (No
such file or directory)

01-19 06:10:42.559 14248 14337 E BugleRcsEngine:
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.buildRcsState(SourceFile:64)

01-19 06:10:42.559 14248 14337 E BugleRcsEngine:
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.getRcsState(SourceFile:5)

01-19 06:10:42.864 14248 14260 W RcsProvisioning: Failed to read
configuration:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:42.865 14248 14260 W RcsProvisioning:
java.io.FileNotFoundException:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:42.865 14248 14260 W RcsProvisioning: at
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.onMigrationComplete(SourceFile:23)

01-19 06:10:43.060 14248 14260 W RcsProvisioning: Failed to read
configuration:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:43.060 14248 14260 W RcsProvisioning:
java.io.FileNotFoundException:
/data/user/0/com.google.android.apps.messaging/files/rcsconfig (No such
file or directory)

01-19 06:10:43.060 14248 14260 W RcsProvisioning: at
com.google.android.apps.messaging.rcsmigration.RcsStateProvider.onMigrationComplete(SourceFile:38)

**Comment by leo26212** [comment]
Sorry guys just learning bare with me..

**Comment by MiguelNdeCarvalho** [comment]
@leo26212 There is no problem with that mate. Just read the guide that I sent to you and try to take a logcat 😁

**Comment by leo26212** [comment]
Ok on it thanks for the help

**Comment by leo26212** [comment]
Ok i see know give me few to get to my pc i just have to plug in and run
the cmds

**Comment by leo26212** [comment]
this is taking forever lol 

Give me even more respect for yall.. 




https://drive.google.com/file/d/1rtawFaZeFxTUZ2hcXL4ip84Cp1xSLknK/view?usp=drivesdk

🤦‍♂️🤦‍♂️

I don't have telegram but im on goggle+lol

**Comment by leo26212** [comment]
Did you receive that?

**Comment by Akianonymus** [comment]
Closing this, contact your maintainer to update rom, ROM is fine

**Comment by leo26212** [comment]
well I wouldn't know it took so long to receive any replies I have already got a new phone

**Comment by Akianonymus** [comment]
@leo26212 😂 lmao

**Comment by ironmerc** [comment]
@leo26212 Lol
